<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8VUSPTS" failures="1" tests="16" name="Test 1" time="8.603" errors="0" timestamp="2024-11-29T15:50:32 EET">
  <testcase classname="TestCases.TestExecution" name="TC1" time="0.168"/>
  <testcase classname="TestCases.TestExecution" name="TC2" time="0.169"/>
  <testcase classname="TestCases.TestExecution" name="TC3" time="0.271"/>
  <testcase classname="TestCases.TestExecution" name="TC4" time="0.253"/>
  <testcase classname="TestCases.TestExecution" name="TC5" time="0.016"/>
  <testcase classname="TestCases.TestExecution" name="TC6" time="0.028"/>
  <testcase classname="TestCases.TestExecution" name="TC7" time="0.27"/>
  <testcase classname="TestCases.TestExecution" name="TC8" time="0.255"/>
  <testcase classname="TestCases.TestExecution" name="TC9" time="0.065"/>
  <testcase classname="TestCases.TestExecution" name="TC10" time="3.292"/>
  <testcase classname="TestCases.TestExecution" name="TC11" time="0.021"/>
  <testcase classname="TestCases.TestExecution" name="TC12" time="0.479"/>
  <testcase classname="TestCases.TestExecution" name="TC13" time="0.532"/>
  <testcase classname="TestCases.TestExecution" name="TC14" time="0.159"/>
  <testcase classname="TestCases.TestExecution" name="TC15" time="0.207"/>
  <testcase classname="TestCases.TestExecution" name="TC16" time="0.09">
    <failure type="java.lang.AssertionError" message="expected [1Thank you for your order!] but found [Thank you for your order!]">
      <![CDATA[java.lang.AssertionError: expected [1Thank you for your order!] but found [Thank you for your order!]
at TestCases.TestExecution.TC16(TestExecution.java:142)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- TC16 -->
</testsuite> <!-- Test 1 -->
